# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyvaluestore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keyvaluestore.proto',
  package='keyvaluestore',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13keyvaluestore.proto\x12\rkeyvaluestore\"\x1c\n\rLookupRequest\x12\x0b\n\x03key\x18\x01 \x01(\x03\"\x1f\n\x0eLookupResponse\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1c\n\x0cResponseCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"$\n\x06KVPair\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02\x32\xa1\x01\n\rKeyValueStore\x12J\n\tGetValues\x12\x1c.keyvaluestore.LookupRequest\x1a\x1d.keyvaluestore.LookupResponse\"\x00\x12\x44\n\x0cInsertValues\x12\x15.keyvaluestore.KVPair\x1a\x1b.keyvaluestore.ResponseCode\"\x00\x62\x06proto3'
)




_LOOKUPREQUEST = _descriptor.Descriptor(
  name='LookupRequest',
  full_name='keyvaluestore.LookupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='keyvaluestore.LookupRequest.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=66,
)


_LOOKUPRESPONSE = _descriptor.Descriptor(
  name='LookupResponse',
  full_name='keyvaluestore.LookupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='keyvaluestore.LookupResponse.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=99,
)


_RESPONSECODE = _descriptor.Descriptor(
  name='ResponseCode',
  full_name='keyvaluestore.ResponseCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='keyvaluestore.ResponseCode.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=129,
)


_KVPAIR = _descriptor.Descriptor(
  name='KVPair',
  full_name='keyvaluestore.KVPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='keyvaluestore.KVPair.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='keyvaluestore.KVPair.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['LookupRequest'] = _LOOKUPREQUEST
DESCRIPTOR.message_types_by_name['LookupResponse'] = _LOOKUPRESPONSE
DESCRIPTOR.message_types_by_name['ResponseCode'] = _RESPONSECODE
DESCRIPTOR.message_types_by_name['KVPair'] = _KVPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LookupRequest = _reflection.GeneratedProtocolMessageType('LookupRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPREQUEST,
  '__module__' : 'keyvaluestore_pb2'
  # @@protoc_insertion_point(class_scope:keyvaluestore.LookupRequest)
  })
_sym_db.RegisterMessage(LookupRequest)

LookupResponse = _reflection.GeneratedProtocolMessageType('LookupResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPRESPONSE,
  '__module__' : 'keyvaluestore_pb2'
  # @@protoc_insertion_point(class_scope:keyvaluestore.LookupResponse)
  })
_sym_db.RegisterMessage(LookupResponse)

ResponseCode = _reflection.GeneratedProtocolMessageType('ResponseCode', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECODE,
  '__module__' : 'keyvaluestore_pb2'
  # @@protoc_insertion_point(class_scope:keyvaluestore.ResponseCode)
  })
_sym_db.RegisterMessage(ResponseCode)

KVPair = _reflection.GeneratedProtocolMessageType('KVPair', (_message.Message,), {
  'DESCRIPTOR' : _KVPAIR,
  '__module__' : 'keyvaluestore_pb2'
  # @@protoc_insertion_point(class_scope:keyvaluestore.KVPair)
  })
_sym_db.RegisterMessage(KVPair)



_KEYVALUESTORE = _descriptor.ServiceDescriptor(
  name='KeyValueStore',
  full_name='keyvaluestore.KeyValueStore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=331,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetValues',
    full_name='keyvaluestore.KeyValueStore.GetValues',
    index=0,
    containing_service=None,
    input_type=_LOOKUPREQUEST,
    output_type=_LOOKUPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertValues',
    full_name='keyvaluestore.KeyValueStore.InsertValues',
    index=1,
    containing_service=None,
    input_type=_KVPAIR,
    output_type=_RESPONSECODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYVALUESTORE)

DESCRIPTOR.services_by_name['KeyValueStore'] = _KEYVALUESTORE

# @@protoc_insertion_point(module_scope)
